### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by AshabaJasper** [gdsc-ys/gdsc-ys.github.io#3]
The application is somewhat big and a takes sometime to show up, you might want to consider react lazy loading, via your index.js file:

React's React.lazy function to lazily load the App component. This can significantly improve performance especially in this case, with the styling and assests:

const App = React.lazy(() => import('@/App'));

Otherwise the code is already amazing!

**Comment by whatisyourname0** [comment]
Hi @AshabaJasper, I'm the main author of our GDSC website, gdsc-ys.github.io.

Thanks for your advice, and I appreciate your comment of using lazy loading technique!
